server:
  port: 8888

spring:
  application:
    name: PetAdoptionConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PetAdoptionCenter88/Configs.git
          clone-on-start: true
